/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.honeybadgers.flltutorial.ui.main;

import java.awt.dnd.MouseDragGestureRecognizer;
import javax.swing.JLayeredPane;
import javax.swing.JPanel;

/**
 *
 * @author chingaman
 */
public class ContentPanel extends javax.swing.JPanel {

    /**
     * Creates new form ContentPanel
     */
    public ContentPanel() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        layeredContentPane = new javax.swing.JLayeredPane();
        answersPanel = new javax.swing.JPanel();
        optionsPanel = new javax.swing.JPanel();
        dragPanel = new javax.swing.JPanel();

        answersPanel.setBackground(new java.awt.Color(204, 204, 204));

        org.jdesktop.layout.GroupLayout answersPanelLayout = new org.jdesktop.layout.GroupLayout(answersPanel);
        answersPanel.setLayout(answersPanelLayout);
        answersPanelLayout.setHorizontalGroup(
            answersPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 320, Short.MAX_VALUE)
        );
        answersPanelLayout.setVerticalGroup(
            answersPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 400, Short.MAX_VALUE)
        );

        answersPanel.setBounds(0, 0, 320, 400);
        layeredContentPane.add(answersPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        optionsPanel.setBackground(new java.awt.Color(255, 255, 255));
        optionsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dragPanel.setBackground(new java.awt.Color(255, 153, 0));

        org.jdesktop.layout.GroupLayout dragPanelLayout = new org.jdesktop.layout.GroupLayout(dragPanel);
        dragPanel.setLayout(dragPanelLayout);
        dragPanelLayout.setHorizontalGroup(
            dragPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 100, Short.MAX_VALUE)
        );
        dragPanelLayout.setVerticalGroup(
            dragPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 100, Short.MAX_VALUE)
        );

        optionsPanel.add(dragPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        optionsPanel.setBounds(320, 0, 280, 400);
        layeredContentPane.add(optionsPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layeredContentPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layeredContentPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel answersPanel;
    private javax.swing.JPanel dragPanel;
    private javax.swing.JLayeredPane layeredContentPane;
    private javax.swing.JPanel optionsPanel;
    // End of variables declaration//GEN-END:variables
}
