/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.honeybadgers.flltutorial.ui.main.navigation;

import javax.swing.JScrollPane;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author chingaman
 */
public class InstructionsPanel extends javax.swing.JPanel {

    /**
     * Creates new form InstructionsPanel
     */
    public InstructionsPanel() {
        initComponents();
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();

        setBackground(new java.awt.Color(120, 120, 120));

        jScrollPane1.setBackground(new java.awt.Color(120, 120, 120));

        jEditorPane1.setBackground(new java.awt.Color(120, 120, 120));
        jEditorPane1.setContentType("text/html"); // NOI18N
        jEditorPane1.setText("<html>\n  <head>\n\n  </head>\n  <body style=\"background:#787878; margin-left: 10px\">\n    <h2>Instructions</h2>\n    <h3 style=\"color:yellow\">Yellow Panels</h3>\n\t<p style=\"margin-top:-20px; margin-left: 5px\"> This means you need to drag a panel from the yellow panels on the right side\n\tto the yellow panels on the center stage.</p>\n    <h3 style=\"color:#00FF00\">Light Green Panels</h3>\n\t<p style=\"margin-top:-20px; margin-left: 5px\">This means correct, but not finished. You should continue to finish panels related to this panel on the stage by clicking this light green panel on the stage.</p>\n    <h3 style=\"color:#009933\">Dark Green Panels</h3>\n\t<p style=\"margin-top:-20px; margin-left: 5px\">This means correct, and finished. You don't need to do anything for this panels</p>\n    <h3 style=\"color:red\">Red Panels</h3>\n\t<p style=\"margin-top:-20px; margin-left: 5px\">means incorrect</p>\n  </body>\n</html>\n");
        jEditorPane1.setDragEnabled(false);
        jEditorPane1.setFocusTraversalKeysEnabled(false);
        jEditorPane1.setFocusable(false);
        jEditorPane1.setRequestFocusEnabled(false);
        jEditorPane1.setBorder(new EmptyBorder(0,0,0,0));
        jEditorPane1.setVerifyInputWhenFocusTarget(false);
        jScrollPane1.setViewportView(jEditorPane1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
