/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.honeybadgers.flltutorial.ui.begin;

import com.honeybadgers.flltutorial.model.TutorialBase;
import java.awt.Component;
import javax.swing.JPanel;

/**
 *
 * @author chingaman
 */
public class ProjectPanel extends javax.swing.JPanel {

    /**
     * Creates new form tutorialPanel
     */
    private TutorialBase tutorialBase;
    public ProjectPanel(TutorialBase tutorialBase) {
        initComponents();
        this.tutorialBase = tutorialBase;
        this.titleLabel.setText(tutorialBase.getTitle());
        this.authorLabel.setText(tutorialBase.getAuthor());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        layeredPane = new javax.swing.JLayeredPane();
        tutorialContentPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        authorLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        beaconPanel = new javax.swing.JPanel();

        layeredPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        layeredPane.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                tutorialPanelResized(evt);
            }
        });

        tutorialContentPanel.setBackground(new java.awt.Color(153, 153, 153));

        titleLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        titleLabel.setText("project name");

        authorLabel.setText("by team name");

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        org.jdesktop.layout.GroupLayout tutorialContentPanelLayout = new org.jdesktop.layout.GroupLayout(tutorialContentPanel);
        tutorialContentPanel.setLayout(tutorialContentPanelLayout);
        tutorialContentPanelLayout.setHorizontalGroup(
            tutorialContentPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(tutorialContentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(tutorialContentPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane1)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, tutorialContentPanelLayout.createSequentialGroup()
                        .add(0, 0, Short.MAX_VALUE)
                        .add(authorLabel))
                    .add(tutorialContentPanelLayout.createSequentialGroup()
                        .add(titleLabel)
                        .add(0, 308, Short.MAX_VALUE)))
                .addContainerGap())
        );
        tutorialContentPanelLayout.setVerticalGroup(
            tutorialContentPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(tutorialContentPanelLayout.createSequentialGroup()
                .add(12, 12, 12)
                .add(titleLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(authorLabel)
                .addContainerGap())
        );

        tutorialContentPanel.setBounds(0, 0, 410, 150);
        layeredPane.add(tutorialContentPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        beaconPanel.setBackground(new java.awt.Color(255, 153, 153));
        beaconPanel.setOpaque(false);

        org.jdesktop.layout.GroupLayout beaconPanelLayout = new org.jdesktop.layout.GroupLayout(beaconPanel);
        beaconPanel.setLayout(beaconPanelLayout);
        beaconPanelLayout.setHorizontalGroup(
            beaconPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 404, Short.MAX_VALUE)
        );
        beaconPanelLayout.setVerticalGroup(
            beaconPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 144, Short.MAX_VALUE)
        );

        beaconPanel.setBounds(0, 0, 404, 144);
        layeredPane.add(beaconPanel, javax.swing.JLayeredPane.DRAG_LAYER);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layeredPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layeredPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tutorialPanelResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tutorialPanelResized
        this.beaconPanel.setSize(layeredPane.getSize());
        this.tutorialContentPanel.setSize(layeredPane.getSize());
        this.tutorialContentPanel.revalidate();
        this.beaconPanel.revalidate();
    }//GEN-LAST:event_tutorialPanelResized

    public Component getBeacon()
    {
        return (Component)this.beaconPanel;
    }
    
    public static TutorialBase getTutorialBaseFromBeacon(Component beacon)
    {
        if(beacon instanceof JPanel)
        {
            ProjectPanel tutorialPanel = (ProjectPanel)beacon.getParent().getParent();
            return tutorialPanel.tutorialBase;
        }
        return null;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel authorLabel;
    private javax.swing.JPanel beaconPanel;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLayeredPane layeredPane;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel tutorialContentPanel;
    // End of variables declaration//GEN-END:variables
}
