/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.honeybadgers.flltutorial.ui.begin;

/**
 *
 * @author chingaman
 */
public class TutorialPanel extends javax.swing.JPanel {

    /**
     * Creates new form tutorialPanel
     */
    public TutorialPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        layeredPane = new javax.swing.JLayeredPane();
        tutorialContentPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        authorLabel = new javax.swing.JLabel();
        jTextArea1 = new javax.swing.JTextArea();
        beaconPanel = new javax.swing.JPanel();

        layeredPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        layeredPane.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                tutorialPanelResized(evt);
            }
        });

        tutorialContentPanel.setBackground(new java.awt.Color(153, 153, 153));

        titleLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        titleLabel.setText("tutorial title");

        authorLabel.setText("by author");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("description");

        org.jdesktop.layout.GroupLayout tutorialContentPanelLayout = new org.jdesktop.layout.GroupLayout(tutorialContentPanel);
        tutorialContentPanel.setLayout(tutorialContentPanelLayout);
        tutorialContentPanelLayout.setHorizontalGroup(
            tutorialContentPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(tutorialContentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(tutorialContentPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, tutorialContentPanelLayout.createSequentialGroup()
                        .add(0, 0, Short.MAX_VALUE)
                        .add(authorLabel))
                    .add(tutorialContentPanelLayout.createSequentialGroup()
                        .add(titleLabel)
                        .add(0, 318, Short.MAX_VALUE)))
                .addContainerGap())
            .add(tutorialContentPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(org.jdesktop.layout.GroupLayout.TRAILING, tutorialContentPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .add(jTextArea1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        tutorialContentPanelLayout.setVerticalGroup(
            tutorialContentPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(tutorialContentPanelLayout.createSequentialGroup()
                .add(12, 12, 12)
                .add(titleLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 99, Short.MAX_VALUE)
                .add(authorLabel)
                .addContainerGap())
            .add(tutorialContentPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(tutorialContentPanelLayout.createSequentialGroup()
                    .add(35, 35, 35)
                    .add(jTextArea1)
                    .add(35, 35, 35)))
        );

        tutorialContentPanel.setBounds(0, 0, 410, 150);
        layeredPane.add(tutorialContentPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        beaconPanel.setBackground(new java.awt.Color(255, 153, 153));
        beaconPanel.setOpaque(false);

        org.jdesktop.layout.GroupLayout beaconPanelLayout = new org.jdesktop.layout.GroupLayout(beaconPanel);
        beaconPanel.setLayout(beaconPanelLayout);
        beaconPanelLayout.setHorizontalGroup(
            beaconPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 404, Short.MAX_VALUE)
        );
        beaconPanelLayout.setVerticalGroup(
            beaconPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 144, Short.MAX_VALUE)
        );

        beaconPanel.setBounds(0, 0, 404, 144);
        layeredPane.add(beaconPanel, javax.swing.JLayeredPane.DRAG_LAYER);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layeredPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layeredPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tutorialPanelResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tutorialPanelResized
        this.beaconPanel.setSize(layeredPane.getSize());
        this.tutorialContentPanel.setSize(layeredPane.getSize());
        this.tutorialContentPanel.revalidate();
        this.beaconPanel.revalidate();
    }//GEN-LAST:event_tutorialPanelResized

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel authorLabel;
    private javax.swing.JPanel beaconPanel;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLayeredPane layeredPane;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel tutorialContentPanel;
    // End of variables declaration//GEN-END:variables
}
