/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.honeybadgers.flltutorial.ui.main.content.utilities;

import com.honeybadgers.flltutorial.model.Option;
import static com.honeybadgers.flltutorial.ui.main.content.utilities.OptionPanel.OptionState.CORRECT;
import static com.honeybadgers.flltutorial.ui.main.content.utilities.OptionPanel.OptionState.FINISHED;
import static com.honeybadgers.flltutorial.ui.main.content.utilities.OptionPanel.OptionState.HIDDEN_OCCUPY;
import static com.honeybadgers.flltutorial.ui.main.content.utilities.OptionPanel.OptionState.INCORRECT;
import static com.honeybadgers.flltutorial.ui.main.content.utilities.OptionPanel.OptionState.NORMAL;
import static com.honeybadgers.flltutorial.ui.main.content.utilities.OptionPanel.OptionState.UNOCCUPIED;
import java.awt.Color;
import java.awt.Component;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLayeredPane;
import javax.swing.JPanel;
import javax.swing.JTextArea;

/**
 *
 * @author chingaman
 */
public class PictureOptionPanel extends OptionPanel {

    /**
     * Creates new form PictureOptionPanel
     */
    public PictureOptionPanel(Option option) {
        initComponents();
        
        if(option == null)
        {
            this.iconDisplay.setIcon(null);
            this.iconDisplay.setText("");
            this.setState(NORMAL);
            return;
        }
                        
        System.out.println(option.getImagePath());
        File pictureFile = new File("/Users/chingaman/Desktop/hb-repo/FLLTutorial/src/main/resources/sampleTutorial/"+option.getImagePath());
        if(pictureFile.exists())
        {
            try {
                
                BufferedImage img = ImageIO.read(pictureFile);
                System.out.println(""+img.getHeight()+" "+img.getWidth());
                System.out.println(""+this.contentPanel.getSize());
                int sizeY = this.contentPanel.getSize().height - 100;
                Image image = img.getScaledInstance(sizeY, sizeY, Image.SCALE_SMOOTH);
                System.out.println(""+sizeY);
                this.iconDisplay.setIcon(new ImageIcon(image));
                
            } catch (IOException ex) {
                Logger.getLogger(PictureOptionPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        this.iconDisplay.setText("");   
        this.setState(NORMAL);
    }

    public static void main(String[] args)
    {
        JFrame frame = new JFrame("FrameDemo");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().add(new PictureOptionPanel(null));
        frame.pack();
        frame.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        layeredPane = new javax.swing.JLayeredPane();
        contentPanel = new javax.swing.JPanel();
        iconDisplay = new javax.swing.JLabel();
        beaconPanel = new javax.swing.JPanel();

        setLayout(new java.awt.GridLayout(1, 1));

        layeredPane.setPreferredSize(new java.awt.Dimension(200, 200));
        layeredPane.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                layeredPaneResize(evt);
            }
        });

        contentPanel.setLayout(new java.awt.BorderLayout());

        iconDisplay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconDisplay.setIcon(new javax.swing.ImageIcon("/Users/chingaman/Desktop/hb-repo/FLLTutorial/src/main/resources/sampleTutorial/media/motion-FourWheels.png")); // NOI18N
        iconDisplay.setText("default title\n");
        iconDisplay.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        iconDisplay.setDisabledIcon(new javax.swing.ImageIcon("/Users/chingaman/Desktop/hb-repo/FLLTutorial/src/main/resources/sampleTutorial/media/ballDetection-ColorSensor.png")); // NOI18N
        iconDisplay.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        iconDisplay.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        contentPanel.add(iconDisplay, java.awt.BorderLayout.CENTER);

        contentPanel.setBounds(0, 0, 210, 220);
        layeredPane.add(contentPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        beaconPanel.setOpaque(false);

        org.jdesktop.layout.GroupLayout beaconPanelLayout = new org.jdesktop.layout.GroupLayout(beaconPanel);
        beaconPanel.setLayout(beaconPanelLayout);
        beaconPanelLayout.setHorizontalGroup(
            beaconPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 210, Short.MAX_VALUE)
        );
        beaconPanelLayout.setVerticalGroup(
            beaconPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 210, Short.MAX_VALUE)
        );

        beaconPanel.setBounds(0, 0, 210, 210);
        layeredPane.add(beaconPanel, javax.swing.JLayeredPane.DRAG_LAYER);

        add(layeredPane);
    }// </editor-fold>//GEN-END:initComponents

    private void layeredPaneResize(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_layeredPaneResize
        this.beaconPanel.setSize(this.layeredPane.getSize());
        this.contentPanel.setSize(this.layeredPane.getSize());
        this.iconDisplay.setSize(this.beaconPanel.getSize());
        
        this.beaconPanel.revalidate();
        this.contentPanel.revalidate();
        this.iconDisplay.revalidate();
    }//GEN-LAST:event_layeredPaneResize

    @Override
    public OptionPanel copy()
    {
            OptionPanel optionPanel = new PictureOptionPanel(this.option);
            return optionPanel;
    }
    /**
     * This object method transfers in a give option, and stores it. It may not show
     * the option immediately, unless the state of the option panel is NORMAL.
     * 
     * @param option the Option object that will be stored in this OptionPanel
     */
    
    @Override
    public void transferOption(Option option)
    {
        this.option = option;
        if(this.iconDisplay != null)
        {
            //try
            //{this.description.getDocument().insertString(0, this.option.getDescription(), null);}
            //catch(Exception e){System.err.println("OptionPanel - exception");}
            this.iconDisplay.setText(option.getDescription());
            this.revalidate();
        }
    }
    /**
     * This object method sets the state of this OptionPanel. It is mainly used for display
     * purposes.
     * 
     * @param state the enumerate type OptionPanel.OptionState which denotes the state of the panel.
     */
    @Override
    public void setState(OptionState state)
    {
        this.state = state;
        switch(this.state)
        {
            case NORMAL: /*beginning state*/
                this.setOpaque(true);
                this.contentPanel.setBackground(Color.YELLOW);
                this.setBorder(BorderFactory.createLineBorder(Color.BLACK));
                break;
            case HIDDEN_OCCUPY:
                this.contentPanel.setBackground(Color.GRAY);
                this.setBorder(null);
                break;
            case UNOCCUPIED:
                this.contentPanel.setBackground(Color.LIGHT_GRAY);
                this.setBorder(BorderFactory.createLineBorder(Color.BLACK));
            case CORRECT:
                this.setOpaque(true);
                this.contentPanel.setBackground(Color.GREEN);
                this.setBorder(BorderFactory.createLineBorder(Color.BLACK));
                break;
            case INCORRECT:
                this.setOpaque(true);
                this.contentPanel.setBackground(Color.RED);
                this.setBorder(BorderFactory.createLineBorder(Color.BLACK));
                break;
           case FINISHED:
                this.setOpaque(true);
                this.contentPanel.setBackground(Color.GREEN.darker());
                this.setBorder(BorderFactory.createLineBorder(Color.BLACK));
                break;
            default:
                break;
        }
    }
  
    @Override
    public OptionState getState()
    {
        return this.state;
    }
    
   
    @Override
    public Option getOption() {
        return option;
    }
    /**
     * Returns an Object that covers the whole panel and can be used to track, and
     * receive events on the given option panel.
     * 
     * @return 
     */
    @Override
    public Component getBeacon()
    {
        return this.beaconPanel;
    }
    /**
     * Returns the corresponding option panel from the input beacon.
     * 
     * @param object
     * @return 
     */
    public static OptionPanel getOptionPanelFromBeaconSpecific(Component object)
    {
        System.out.println(object.getParent().getParent().getParent().getParent());
        return (OptionPanel)object.getParent().getParent().getParent().getParent();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel beaconPanel;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JLabel iconDisplay;
    private javax.swing.JLayeredPane layeredPane;
    // End of variables declaration//GEN-END:variables
}
