/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.honeybadgers.flltutorial.ui.main.content.utilities;

import com.honeybadgers.flltutorial.model.Option;
import java.awt.Color;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author chingaman
 */
public class PictureOptionPanel extends javax.swing.JPanel {

    /**
     * Creates new form PictureOptionPanel
     */
    public PictureOptionPanel(Option option) {
        initComponents();
        this.contentPanel.setBackground(Color.red);
        File dir = new File(".");
        
        System.out.println(""+dir.getAbsolutePath());
        File pictureFile = new File("/Users/chingaman/Desktop/hb-repo/FLLTutorial/src/main/resources/sampleTutorial/media/ballDetection-ColorSensor.png");
        if(pictureFile.exists())
        {
            try {
                
                BufferedImage img = ImageIO.read(pictureFile);
                System.out.println(""+img.getHeight()+" "+img.getWidth());
                System.out.println(""+this.contentPanel.getSize());
                int sizeY = this.contentPanel.getSize().height - 100;
                Image image = img.getScaledInstance(sizeY, sizeY, Image.SCALE_SMOOTH);
                System.out.println(""+sizeY);
                this.iconDisplay.setIcon(new ImageIcon(image));
                
            } catch (IOException ex) {
                Logger.getLogger(PictureOptionPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }

    public static void main(String[] args)
    {
        JFrame frame = new JFrame("FrameDemo");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().add(new PictureOptionPanel(null));
        frame.pack();
        frame.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        layeredPane = new javax.swing.JLayeredPane();
        contentPanel = new javax.swing.JPanel();
        iconDisplay = new javax.swing.JLabel();
        beaconPanel = new javax.swing.JPanel();

        setLayout(new java.awt.GridLayout(1, 1));

        layeredPane.setPreferredSize(new java.awt.Dimension(200, 200));
        layeredPane.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                layeredPaneResize(evt);
            }
        });

        contentPanel.setLayout(new java.awt.BorderLayout());

        iconDisplay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconDisplay.setIcon(new javax.swing.ImageIcon("/Users/chingaman/Desktop/hb-repo/FLLTutorial/src/main/resources/sampleTutorial/media/motion-FourWheels.png")); // NOI18N
        iconDisplay.setText("default title\n");
        iconDisplay.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        iconDisplay.setDisabledIcon(new javax.swing.ImageIcon("/Users/chingaman/Desktop/hb-repo/FLLTutorial/src/main/resources/sampleTutorial/media/ballDetection-ColorSensor.png")); // NOI18N
        iconDisplay.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        iconDisplay.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        contentPanel.add(iconDisplay, java.awt.BorderLayout.CENTER);

        contentPanel.setBounds(0, 0, 210, 220);
        layeredPane.add(contentPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        beaconPanel.setOpaque(false);

        org.jdesktop.layout.GroupLayout beaconPanelLayout = new org.jdesktop.layout.GroupLayout(beaconPanel);
        beaconPanel.setLayout(beaconPanelLayout);
        beaconPanelLayout.setHorizontalGroup(
            beaconPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 210, Short.MAX_VALUE)
        );
        beaconPanelLayout.setVerticalGroup(
            beaconPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 210, Short.MAX_VALUE)
        );

        beaconPanel.setBounds(0, 0, 210, 210);
        layeredPane.add(beaconPanel, javax.swing.JLayeredPane.DRAG_LAYER);

        add(layeredPane);
    }// </editor-fold>//GEN-END:initComponents

    private void layeredPaneResize(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_layeredPaneResize
        this.beaconPanel.setSize(this.layeredPane.getSize());
        this.contentPanel.setSize(this.layeredPane.getSize());
        this.iconDisplay.setSize(this.beaconPanel.getSize());
        
        this.beaconPanel.revalidate();
        this.contentPanel.revalidate();
        this.iconDisplay.revalidate();
    }//GEN-LAST:event_layeredPaneResize

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel beaconPanel;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JLabel iconDisplay;
    private javax.swing.JLayeredPane layeredPane;
    // End of variables declaration//GEN-END:variables
}
